framework:
<<<<<<< HEAD
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
=======
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
>>>>>>> 32bd6da12f12b3ad475b0b6146ec837cbb22b8e1
